//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rxx.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rxx.Properties.Text", typeof(Text).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposed subscription..
        /// </summary>
        internal static string DefaultDisposedSubscriptionMessage {
            get {
                return ResourceManager.GetString("DefaultDisposedSubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing subscription..
        /// </summary>
        internal static string DefaultDisposingSubscriptionMessage {
            get {
                return ResourceManager.GetString("DefaultDisposingSubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence completed..
        /// </summary>
        internal static string DefaultOnCompletedMessage {
            get {
                return ResourceManager.GetString("DefaultOnCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed to observable..
        /// </summary>
        internal static string DefaultSubscribedMessage {
            get {
                return ResourceManager.GetString("DefaultSubscribedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing to observable..
        /// </summary>
        internal static string DefaultSubscribingMessage {
            get {
                return ResourceManager.GetString("DefaultSubscribingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposed subscription: {0}..
        /// </summary>
        internal static string DisposedSubscriptionFormat {
            get {
                return ResourceManager.GetString("DisposedSubscriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing subscription: {0}..
        /// </summary>
        internal static string DisposingSubscriptionFormat {
            get {
                return ResourceManager.GetString("DisposingSubscriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing FileSystemWatcher buffer size from {0} to {1}..
        /// </summary>
        internal static string FileSystemWatcherBufferChangeFormat {
            get {
                return ResourceManager.GetString("FileSystemWatcherBufferChangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSystemWatcher buffer overflow: {0}.
        /// </summary>
        internal static string FileSystemWatcherBufferOverflowFormat {
            get {
                return ResourceManager.GetString("FileSystemWatcherBufferOverflowFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed to observable: {0}..
        /// </summary>
        internal static string SubscribedFormat {
            get {
                return ResourceManager.GetString("SubscribedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing to observable: {0}..
        /// </summary>
        internal static string SubscribingFormat {
            get {
                return ResourceManager.GetString("SubscribingFormat", resourceCulture);
            }
        }
    }
}
