//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rxx.Parsers.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rxx.Parsers.Properties.Errors", typeof(Errors).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An in-line query cannot be parsed while the grammar is being defined..
        /// </summary>
        internal static string InlineParseNotSupported {
            get {
                return ResourceManager.GetString("InlineParseNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temporary in-line parser does not have a grammar..
        /// </summary>
        internal static string InlineParserWithoutGrammar {
            get {
                return ResourceManager.GetString("InlineParserWithoutGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse cannot be called again until the current parse operation completes..
        /// </summary>
        internal static string ParseCalledWhileParsing {
            get {
                return ResourceManager.GetString("ParseCalledWhileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in parser input sequence..
        /// </summary>
        internal static string ParseExceptionMessage {
            get {
                return ResourceManager.GetString("ParseExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Source index: {2}..
        /// </summary>
        internal static string ParseExceptionMessageOverrideFormat {
            get {
                return ResourceManager.GetString("ParseExceptionMessageOverrideFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is unavailable until after Parse has been called and it has completed successfully..
        /// </summary>
        internal static string ParseNotCalledOrFailed {
            get {
                return ResourceManager.GetString("ParseNotCalledOrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser cannot move the cursor to the end of the input sequence because the current index is ahead of the latest index..
        /// </summary>
        internal static string ParserCannotMoveToEndBackward {
            get {
                return ResourceManager.GetString("ParserCannotMoveToEndBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Next property cannot be read until after Parse is called..
        /// </summary>
        internal static string ParserNextNotReady {
            get {
                return ResourceManager.GetString("ParserNextNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser does not allow new subscriptions until the current parse operation completes..
        /// </summary>
        internal static string ParseSubscribeCalledWhileParsing {
            get {
                return ResourceManager.GetString("ParseSubscribeCalledWhileParsing", resourceCulture);
            }
        }
    }
}
