//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rxx.Labs.Properties
{
  using System;


  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Instructions
  {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Instructions()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rxx.Labs.Properties.Instructions", typeof(Instructions).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Temporarily disable your Internet network adapter or unplug your network cable to observe changes in network connectivity..
    /// </summary>
    internal static string DisableYourNetwork
    {
      get
      {
        return ResourceManager.GetString("DisableYourNetwork", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter a message.
    /// </summary>
    internal static string EnterAMessage
    {
      get
      {
        return ResourceManager.GetString("EnterAMessage", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter a URL.
    /// </summary>
    internal static string EnterAUrl
    {
      get
      {
        return ResourceManager.GetString("EnterAUrl", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter a value for Bar.
    /// </summary>
    internal static string EnterAValueForBar
    {
      get
      {
        return ResourceManager.GetString("EnterAValueForBar", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter a value for Baz.
    /// </summary>
    internal static string EnterAValueForBaz
    {
      get
      {
        return ResourceManager.GetString("EnterAValueForBaz", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter a value for Foo.
    /// </summary>
    internal static string EnterAValueForFoo
    {
      get
      {
        return ResourceManager.GetString("EnterAValueForFoo", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter the response.
    /// </summary>
    internal static string EnterTheResponse
    {
      get
      {
        return ResourceManager.GetString("EnterTheResponse", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Double-click an item to show its details.  Right-mouse click to reset..
    /// </summary>
    internal static string EventSubscriptionLabDoubleClick
    {
      get
      {
        return ResourceManager.GetString("EventSubscriptionLabDoubleClick", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mouse over an item to show its preview..
    /// </summary>
    internal static string EventSubscriptionLabMouseOver
    {
      get
      {
        return ResourceManager.GetString("EventSubscriptionLabMouseOver", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Input.
    /// </summary>
    internal static string Input
    {
      get
      {
        return ResourceManager.GetString("Input", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter text at the prompt.  To end this lab, just press Enter..
    /// </summary>
    internal static string IxTraceLab
    {
      get
      {
        return ResourceManager.GetString("IxTraceLab", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Press + to add a subscriber.
    ///Press - to remove a subscriber.
    ///Press any other key to cancel.
    ///
    ///Add one subscriber and wait for some notifications.  Then add another subscriber and notice that the previous notifications are replayed to the new subscriber.
    ///
    ///Now remove all of the subscribers to clear the buffer.  Finally, add a new subscriber and notice that the previous notifications are not replayed..
    /// </summary>
    internal static string MulticastLab
    {
      get
      {
        return ResourceManager.GetString("MulticastLab", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter a basic math expression and it will be evaluated.  Only positive and negative whole numbers are supported.
    ///Expressions have one left operand, then an operator, and one right operand.
    ///The only supported operators are: + - * /
    ///You may enter multiple expressions on the same line by separating them with one or more spaces; e.g.,   4*4     1  -  9      -3 + 100
    ///Press Enter without typing an expression to end this lab..
    /// </summary>
    internal static string ParserArithmeticLab
    {
      get
      {
        return ResourceManager.GetString("ParserArithmeticLab", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter any of the following key combinations.  Do not include spaces between characters.
    ///
    ///H I
    ///B E E P
    ///1 2 3
    ///&lt; &gt;
    ///S T O P.
    /// </summary>
    internal static string ParserKeyComboLab
    {
      get
      {
        return ResourceManager.GetString("ParserKeyComboLab", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter a stock value (positive integer) at the prompt.  Repeat as desired.  Enter RND at the prompt to produce 5 random values.  To quit, enter an invalid value or press Enter without any value..
    /// </summary>
    internal static string ParserStockTickerLab
    {
      get
      {
        return ResourceManager.GetString("ParserStockTickerLab", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Use a real device instead of the Windows Phone Emulator to search for appointments..
    /// </summary>
    internal static string PhoneEmulatorAppointmentsSuggestion
    {
      get
      {
        return ResourceManager.GetString("PhoneEmulatorAppointmentsSuggestion", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to If you&apos;re using the Windows Phone Emulator, try searching for &quot;lopez&quot;..
    /// </summary>
    internal static string PhoneEmulatorContactsSuggestion
    {
      get
      {
        return ResourceManager.GetString("PhoneEmulatorContactsSuggestion", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Press any key to cancel....
    /// </summary>
    internal static string PressAnyKeyToCancel
    {
      get
      {
        return ResourceManager.GetString("PressAnyKeyToCancel", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Press any key to continue....
    /// </summary>
    internal static string PressAnyKeyToContinue
    {
      get
      {
        return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Press any key to start the next experiment or press Q to cancel....
    /// </summary>
    internal static string PressAnyKeyToStartNextExperiment
    {
      get
      {
        return ResourceManager.GetString("PressAnyKeyToStartNextExperiment", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Please wait for the sequence to complete....
    /// </summary>
    internal static string WaitForCompletion
    {
      get
      {
        return ResourceManager.GetString("WaitForCompletion", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Please wait for the sequence to fail....
    /// </summary>
    internal static string WaitForError
    {
      get
      {
        return ResourceManager.GetString("WaitForError", resourceCulture);
      }
    }
  }
}
