//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rxx.Labs.Properties
{
  using System;


  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Text
  {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Text()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rxx.Labs.Properties.Text", typeof(Text).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Attaching: {0}.
    /// </summary>
    internal static string AttachingFormat
    {
      get
      {
        return ResourceManager.GetString("AttachingFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0} can execute: {1}.
    /// </summary>
    internal static string CanExecuteChangedFormat
    {
      get
      {
        return ResourceManager.GetString("CanExecuteChangedFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Clicked.
    /// </summary>
    internal static string Clicked
    {
      get
      {
        return ResourceManager.GetString("Clicked", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Client.
    /// </summary>
    internal static string Client
    {
      get
      {
        return ResourceManager.GetString("Client", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Detaching: {0}.
    /// </summary>
    internal static string DetachingFormat
    {
      get
      {
        return ResourceManager.GetString("DetachingFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Dispose: {0}.
    /// </summary>
    internal static string DisposeFormat
    {
      get
      {
        return ResourceManager.GetString("DisposeFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Disposing.
    /// </summary>
    internal static string Disposing
    {
      get
      {
        return ResourceManager.GetString("Disposing", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Disposing: {0}.
    /// </summary>
    internal static string DisposingFormat
    {
      get
      {
        return ResourceManager.GetString("DisposingFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Done.
    /// </summary>
    internal static string Done
    {
      get
      {
        return ResourceManager.GetString("Done", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Duration.
    /// </summary>
    internal static string Duration
    {
      get
      {
        return ResourceManager.GetString("Duration", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Entered.
    /// </summary>
    internal static string Entered
    {
      get
      {
        return ResourceManager.GetString("Entered", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Enter words here..
    /// </summary>
    internal static string EnterWordsHere
    {
      get
      {
        return ResourceManager.GetString("EnterWordsHere", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to &lt;item name=&apos;Item {0}&apos;&gt;
    ///	&lt;preview&gt;Item {0} - Preview&lt;/preview&gt;
    ///	&lt;details&gt;Item {0} - Details&lt;/details&gt;
    ///&lt;/item&gt;.
    /// </summary>
    internal static string EventSubscriptionLabXml
    {
      get
      {
        return ResourceManager.GetString("EventSubscriptionLabXml", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Expression.
    /// </summary>
    internal static string Expression
    {
      get
      {
        return ResourceManager.GetString("Expression", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to First.
    /// </summary>
    internal static string First
    {
      get
      {
        return ResourceManager.GetString("First", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Generated.
    /// </summary>
    internal static string Generated
    {
      get
      {
        return ResourceManager.GetString("Generated", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Generated: {0}.
    /// </summary>
    internal static string GeneratedFormat
    {
      get
      {
        return ResourceManager.GetString("GeneratedFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Host name or IP address.
    /// </summary>
    internal static string HostNameOrAddress
    {
      get
      {
        return ResourceManager.GetString("HostNameOrAddress", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Invalid host name or IP address..
    /// </summary>
    internal static string InvalidHostNameOrIPAddress
    {
      get
      {
        return ResourceManager.GetString("InvalidHostNameOrIPAddress", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The specified interval is invalid..
    /// </summary>
    internal static string InvalidInterval
    {
      get
      {
        return ResourceManager.GetString("InvalidInterval", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The specified port number is out of range..
    /// </summary>
    internal static string InvalidPortOutOfRange
    {
      get
      {
        return ResourceManager.GetString("InvalidPortOutOfRange", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The specified URL is not valid..
    /// </summary>
    internal static string InvalidUrl
    {
      get
      {
        return ResourceManager.GetString("InvalidUrl", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Keys.
    /// </summary>
    internal static string Keys
    {
      get
      {
        return ResourceManager.GetString("Keys", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0} Lab Completed.
    /// </summary>
    internal static string LabCompletedFormat
    {
      get
      {
        return ResourceManager.GetString("LabCompletedFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to This lab requires Windows 8 or higher..
    /// </summary>
    internal static string LabRequiresWindows8OrHigher
    {
      get
      {
        return ResourceManager.GetString("LabRequiresWindows8OrHigher", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0} Lab Starting.
    /// </summary>
    internal static string LabStartingFormat
    {
      get
      {
        return ResourceManager.GetString("LabStartingFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0} observed.
    /// </summary>
    internal static string NamedObserverFormat
    {
      get
      {
        return ResourceManager.GetString("NamedObserverFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Network Addresses.
    /// </summary>
    internal static string NetworkAddresses
    {
      get
      {
        return ResourceManager.GetString("NetworkAddresses", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Network Availability.
    /// </summary>
    internal static string NetworkAvailability
    {
      get
      {
        return ResourceManager.GetString("NetworkAvailability", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to New.
    /// </summary>
    internal static string New
    {
      get
      {
        return ResourceManager.GetString("New", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {null}.
    /// </summary>
    internal static string Null
    {
      get
      {
        return ResourceManager.GetString("Null", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Assigning asyncObj.Message asynchronously....
    /// </summary>
    internal static string ObservableDynamicObjectLabAssigningMessage
    {
      get
      {
        return ResourceManager.GetString("ObservableDynamicObjectLabAssigningMessage", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Calling asyncObj.Calculate() asynchronously....
    /// </summary>
    internal static string ObservableDynamicObjectLabCallingCalculate
    {
      get
      {
        return ResourceManager.GetString("ObservableDynamicObjectLabCallingCalculate", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Calling asyncObj.Ping() asynchronously....
    /// </summary>
    internal static string ObservableDynamicObjectLabCallingPing
    {
      get
      {
        return ResourceManager.GetString("ObservableDynamicObjectLabCallingPing", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Observed.
    /// </summary>
    internal static string Observed
    {
      get
      {
        return ResourceManager.GetString("Observed", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Observing: {0}.
    /// </summary>
    internal static string ObservingFormat
    {
      get
      {
        return ResourceManager.GetString("ObservingFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0}Sequence did not have any values..
    /// </summary>
    internal static string OnCompletedEmptyFormat
    {
      get
      {
        return ResourceManager.GetString("OnCompletedEmptyFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {1}OnCompleted ({0:mm\:ss\.ff}).
    /// </summary>
    internal static string OnCompletedTimeFormat
    {
      get
      {
        return ResourceManager.GetString("OnCompletedTimeFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {1}OnError ({0:mm\:ss\.ff}): {2}.
    /// </summary>
    internal static string OnErrorTimeFormat
    {
      get
      {
        return ResourceManager.GetString("OnErrorTimeFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0}{1}.
    /// </summary>
    internal static string OnNextFormat
    {
      get
      {
        return ResourceManager.GetString("OnNextFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {1}OnNext ({0:mm\:ss\.ff}): {2}.
    /// </summary>
    internal static string OnNextTimeFormat
    {
      get
      {
        return ResourceManager.GetString("OnNextTimeFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Paper.
    /// </summary>
    internal static string Paper
    {
      get
      {
        return ResourceManager.GetString("Paper", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Progress.
    /// </summary>
    internal static string Progress
    {
      get
      {
        return ResourceManager.GetString("Progress", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0}&gt; .
    /// </summary>
    internal static string PromptFormat
    {
      get
      {
        return ResourceManager.GetString("PromptFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Reader.
    /// </summary>
    internal static string Reader
    {
      get
      {
        return ResourceManager.GetString("Reader", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Received {0} byte(s)..
    /// </summary>
    internal static string ReceivedBytesFormat
    {
      get
      {
        return ResourceManager.GetString("ReceivedBytesFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Result.
    /// </summary>
    internal static string Result
    {
      get
      {
        return ResourceManager.GetString("Result", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Rock.
    /// </summary>
    internal static string Rock
    {
      get
      {
        return ResourceManager.GetString("Rock", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Scissors.
    /// </summary>
    internal static string Scissors
    {
      get
      {
        return ResourceManager.GetString("Scissors", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Second.
    /// </summary>
    internal static string Second
    {
      get
      {
        return ResourceManager.GetString("Second", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Sent {0} byte(s)..
    /// </summary>
    internal static string SentBytesFormat
    {
      get
      {
        return ResourceManager.GetString("SentBytesFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Server.
    /// </summary>
    internal static string Server
    {
      get
      {
        return ResourceManager.GetString("Server", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The server has received a request from the client and is waiting to respond..
    /// </summary>
    internal static string ServerReceivedRequest
    {
      get
      {
        return ResourceManager.GetString("ServerReceivedRequest", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The server is starting....
    /// </summary>
    internal static string ServerStarting
    {
      get
      {
        return ResourceManager.GetString("ServerStarting", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The server is stopped..
    /// </summary>
    internal static string ServerStopped
    {
      get
      {
        return ResourceManager.GetString("ServerStopped", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Started: {0}.
    /// </summary>
    internal static string StartedFormat
    {
      get
      {
        return ResourceManager.GetString("StartedFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Subscribing.
    /// </summary>
    internal static string Subscribing
    {
      get
      {
        return ResourceManager.GetString("Subscribing", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Subscribing: {0}.
    /// </summary>
    internal static string SubscribingFormat
    {
      get
      {
        return ResourceManager.GetString("SubscribingFormat", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to You entered &quot;{0}&quot; and the observer removed all of your vowels, spaces and numbers!.
    /// </summary>
    internal static string SubscriptionBindingLabFormatTextResponse
    {
      get
      {
        return ResourceManager.GetString("SubscriptionBindingLabFormatTextResponse", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Third.
    /// </summary>
    internal static string Third
    {
      get
      {
        return ResourceManager.GetString("Third", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tick.
    /// </summary>
    internal static string Tick
    {
      get
      {
        return ResourceManager.GetString("Tick", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Writer.
    /// </summary>
    internal static string Writer
    {
      get
      {
        return ResourceManager.GetString("Writer", resourceCulture);
      }
    }
  }
}
